DROP TABLE IF EXISTS `users`;

CREATE TABLE  `users` (
`id` INT( 11 ) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`name` VARCHAR( 255 ) NOT NULL ,
`phone` VARCHAR( 255 ) NOT NULL ,
`email` VARCHAR( 255 ) NOT NULL,
`description` VARCHAR( 4000 ) NOT NULL
) ENGINE=InnoDB CHECKSUM=1;
